export const snacks = [
  {
    id: 1,
    name: "Lays Chips",
    description: "Lays Chips",
    image: require("./images/lays.png"),
  },
  {
    id: 2,
    name: "Lays Honey Barbecue Chips",
    description: "Lays Honey Barbecue Chips",
    image: require("./images/lays-honey-bbq.png"),
  },
  {
    id: 3,
    name: "Doritos Chips",
    description: "Doritos Chips",
    image: require("./images/doritos.png"),
  },
  {
    id: 4,
    name: "Cheetos Chips",
    description: "Cheetos Chips",
    image: require("./images/cheetos.png"),
  },
  {
    id: 5,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 6,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 7,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 8,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 9,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 10,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 11,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 12,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 13,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 14,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 15,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 16,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 17,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 18,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 19,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 20,
    name: "Tortilla Chips",
    description: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
];
