export const snacks = [
  {
    id: 1,
    name: "Lays Chips",
    price: 1.50,
    image: require("./images/lays.png"),
  },
  {
    id: 2,
    name: "Lays Honey Barbecue Chips",
    price: 1.50,
    image: require("./images/lays-honey-bbq.png"),
  },
  {
    id: 3,
    name: "Doritos Chips",
    price: "1.20",
    image: require("./images/doritos.png"),
  },
  {
    id: 4,
    name: "Cheetos Chips",
    price: "1.30",
    image: require("./images/cheetos.png"),
  },
  {
    id: 5,
    name: "Tortilla Chips",
    price: "1.80",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 6,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 7,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 8,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 9,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 10,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 11,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 12,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 13,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 14,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 15,
    name: "Tortilla Chips",
    price: "Tortilla Chips",
    image: require("./images/tortilla-chips.png"),
  },
  {
    id: 16,
    name: "Nongshim Shin Ramen Noodles",
    price: 1.80,
    image: require("./images/shin-ramen.png"),
  },
  {
    id: 17,
    name: "Nongshim NeoGuri Noodles",
    price: 1.60,
    image: require("./images/nongshim-neoguri.png"),
  },
  {
    id: 18,
    name: "Nongshim Soon Veggie Noodles",
    price: 1.60,
    image: require("./images/nongshim-veggie.png"),
  },
  {
    id: 19,
    name: "Nissin Curry Flavour Noodles",
    price: 1.60,
    image: require("./images/nissin-ramen.png"),
  },
  {
    id: 20,
    name: "Indomie Chicken Flavour Noodles",
    price: 1.20,
    image: require("./images/indomie-chicken.png"),
  },
];
